### ISSUE TITLE
Screenshot missing

### ISSUE THREAD

**Issue by johnalarcon** [zulfgani/generik#1]
Primary screenshot is missing; can be fixed by dropping a `screenshot.png` or `screenshot.jpg` file into the root of the theme.

![image](https://user-images.githubusercontent.com/12477319/54875508-db01d980-4dbd-11e9-973a-9c0df38e1f1d.png)

**Comment by zulfgani** [comment]
Working on a demo site and then will add it in. I'll drop in a generic one for the time being 👍

**Comment by zulfgani** [comment]
Generic screenshot added
![screenshot](https://user-images.githubusercontent.com/48245964/54881132-9e2cf580-4e44-11e9-962e-8508ed726cdf.png)
